name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Change to 'master' if your default branch is named 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build and Deploy
        run: |
          mkdir public
          cp index.html public/
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add public
          git commit -m "Deploy to GitHub Pages"
          git push origin `git subtree split --prefix public HEAD`:gh-pages --force