name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch
    workflow_dispatch:  # Allow manual triggering

permissions:
  pages: write  # Grant write permission to GitHub Pages
  id-token: write  # Grant write permission for OpenID Connect tokens

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2